spring:
  datasource:
    platform: h2

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 0

service:
  defaultMinMs: 100
  defaultMaxMs: 200

eureka:
  client:
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}