# For deployment in Docker containers
spring:
  profiles: docker
  datasource:
    platform: h2

server:
  port: 0

service:
  defaultMinMs: 100
  defaultMaxMs: 200

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
    defaultZone: http://discovery:8761/eureka/